services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ${PWD}/.env
        target: /app/.env
    environment:
      - NODE_ENV=development
